import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <header className="header-area header-sticky">
          <div className="container">
            <nav className="main-nav">
              <a href="/" className="logo">Hypochonder.ai</a>
              <ul className="nav">
                <li><a href="#top" className="active">Home</a></li>
                <li><a href="#services">Leistungen</a></li>
                <li><a href="#about">Über uns</a></li>
              </ul>
              <a className="menu-trigger"><span>Menu</span></a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
